// Panduan fitur Mangalli untuk asisten "Ask Eline" di dashboard. Isi ini
// adalah satu-satunya sumber jawaban soal fitur; perbarui saat fitur berubah.
export const MANGALLI_GUIDE = `
Mangalli is a point-of-sale (POS) for food and beverage businesses: an Android cashier tablet, this web dashboard (app.mangalli.web.id), and an optional digital menu website where customers order from their table or for pickup.

DASHBOARD PAGES (left sidebar)
- Overview: today's sales, paid orders, average order, orders needing attention, sales by hour, payment methods, best sellers, latest orders, cashier shift.
- Orders: every order from the tablet and the digital menu. Tabs: All, Awaiting payment, In progress, Completed, Cancelled. Search by code, customer, or table; filter by From/To date; sort by Newest, Oldest, or Highest total; "Clear" resets filters. Long lists show 25 per page with Previous/Next and page numbers at the bottom. Digital-menu orders paid at the cashier are marked "Paid · Cash" or "Paid · QRIS" here. Orders taken on the tablet are managed on the tablet.
- Kitchen: live board of New, Accepted, Preparing, Ready orders; refreshes every 15 seconds.
- Protected settings: Outlet settings and Team open only after entering your own 6-digit approval PIN (the same PIN as on the cashier tablet), and stay open for 15 minutes on that device; changing the QRIS, payments, tax, outlet profile, opening hours, sync times, the team or branches, and downloading or importing data all need this. It stops anyone who gets hold of a signed-in dashboard from quietly sending customer payments to another QRIS. Five wrong tries pause unlocking for 15 minutes. Without an approval PIN yet, set one in Team first; from then on the lock is on.
- Messages after saving or deleting appear as a short notice at the top of the screen. Deleting or removing anything (products, categories, options, tables, areas, promos, expenses, the store QRIS), deactivating a team member, cancelling or marking an order paid, and importing data always ask to confirm first.
- Account menu (your name at the bottom of the sidebar; on a phone, the round initial at the top right): "Open digital menu", "Order sound on/off" and "Sign out".
- Order sound (account menu, "Order sound on/off", for owners, managers and cashiers when the outlet has a digital menu): when a customer places a digital menu order, the dashboard plays a chime within about 10 seconds, shows a card with the order code, table or Takeaway, customer name and whether it is awaiting payment or already paid, and the browser tab title shows the count, e.g. "(1) Overview". "View order" opens Awaiting payment; "Open kitchen" opens the Kitchen for paid ones. Browsers only allow sound after the first click on the page; if the card shows "Turn on sound", tap it. The choice is saved per browser.
- Shifts: open shifts first, then history 25 per page; who opened and who closed each shift, cash in/out; tablet shifts with opening cash, cash and digital sales, expected vs counted cash and the difference. A dashboard shift can be opened only when selling without the tablet.
- Reports (owner/manager): Today, 7 days, 30 days, 90 days, This month, or any custom range (From and To dates at the top right, up to 366 days). Four tabs, written for owners without a finance background:
  - Summary: a sentence telling how the period went (sales, orders, change versus the same number of days before, and the profit left), cards for Sales, Paid orders, Average order and Profit with the percent change, a daily sales chart (hover a bar for sales and profit), "What stands out" tips (best product, busiest time, discounts, products that didn't sell, short cash drawers), Busy times (a day by hour grid, darker = busier) and Top products.
  - Profit & loss: read from top to bottom. Sales before discounts, minus Discounts, = Sales (the real income from sales, without tax); minus Cost of items sold (from each product's Cost) = Gross profit; minus each expense category and cash paid out at the tablet (Total expenses) = Net profit. Each line has an info icon with a plain explanation. "Good to know" shows Tax collected (belongs to the tax office, not income), Money collected (sales plus tax), refunds and voided items. "Make it accurate" shows how many products have a cost and links to Products and Add expense. Without product costs, profit shows "—".
  - Sales: where orders came from (cashier tablet or digital menu), order types, payment methods, busy times, and a table by day (orders, sales, tax, cash, digital, collected).
  - Products: every product sold with quantity, sales, cost, profit and margin (or "Add cost"), sales by category, and products that didn't sell.
  "CSV" downloads the daily table: orders, sales before discounts, discounts, sales, tax, collected, cash, digital, cost of items, gross profit.
- Expenses (owner/manager, sidebar under Reports): money spent running the outlet so Reports can show net profit. "Add expense": date, amount, category (Ingredients & supplies, Salaries & wages, Rent, Bills & utilities, Marketing & promotion, Equipment & repairs, Transport & delivery, Bank & app fees, Other) and an optional note. Click a row or Edit to change it, or Delete expense at the bottom. Filter by date range and category; "By category" shows where the money went. Cash taken from the drawer on the tablet (Cash in/out) is listed under "Cash out at the tablet" and counted automatically, so don't enter it twice. Every add, change and delete is in the Audit log (Money).
- Daily report email (Outlet settings > "Daily report email"): every active owner and manager gets an email about 30 minutes after closing time (from Opening hours; for hours past midnight like 07:00 to 05:00 it arrives at 05:30 the next morning and covers the whole business day; on closed days with no sales nothing is sent). It shows sales and paid orders with the change versus the day before and the same weekday last week, a one-line summary, money in by payment method, tax collected, estimated gross profit (when products have costs), the five best sellers, closed shifts (balanced, short or over) and cash paid out, and "Needs your attention" (low or no stock, short drawers, unpaid digital menu orders, refunds, open problem reports), plus "Open full report". The owner switches each person on or off; a manager can switch only themselves. "Send me a test" emails today's sales so far to yourself (5 per hour). Every email has "Stop daily reports" at the bottom.
- Product cost (Products > product form > "Cost", optional): what one portion costs to make (ingredients, cup, packaging). Reports use it for profit. Each sale keeps the cost it had when sold, so changing the cost later doesn't change past profit; sales made before any cost was entered use the current cost. Cost changes are in the Audit log.
- Products: search, filter by category/status, sort (Menu order, Name, Price low/high, Newest), 50 per page. "Add product" opens a form: photo (upload JPG/PNG/WebP up to 4 MB, or a link), name, category, price, status (Available, Sold out, Hidden), description, badges (Best seller, Customer favourite), sort order. Saving a new product closes the panel; open the product again to add option groups (e.g. Size, Sugar level, Add-ons) with options and extra prices; mark a group required and set how many choices are allowed. "Save changes" sits at the bottom of the product panel and stays visible while you edit options. Drag the handle (six dots) next to a group or an option to change its order on the tablet and the digital menu. Option names and extra prices can be edited in place (change, then press Enter or the check); "Edit" on a group changes its name, required, and max choices. The switch in the list marks a product sold out instantly. Stock (optional): in the product form tick "Track stock" and fill "Units in stock now". Every order that isn't cancelled (tablet and digital menu) counts down from that number; cancelled or expired orders and voids count back. At 0 the product shows as sold out on the tablet and the digital menu, and nobody can order more than what is left (the digital menu shows "Only N left", the tablet shows "N left"). After a restock or a recount, change the number. The Stock column shows what is left; the status filter has "Low stock (5 or less)" and "Out of stock". Tablet sales made offline are never refused; if they sell more than was in stock, the Audit log shows "Oversold" so the owner can recount. "Delete product" at the bottom of the product form removes it from the tablet and digital menu; past orders keep it (to hide it for a while, set Hidden or Sold out instead).
- Add menu items by chatting with Eline: describe what to add in Ask Eline, for example "add a Drinks category with Es Teh Manis 5rb and Jeruk 6rb, hot or iced (iced +1rb)". Eline prepares a draft with new categories, products, prices and options and gives a "Review and add to the menu" button that opens the Import page with everything filled in; check, edit, then tap Import. Nothing is added until you tap Import. Drafts expire after a day.
- Import with Eline (Products > Import with Eline): upload up to 6 photos of a printed menu or menu board, or paste menu text (e.g. from WhatsApp). Eline reads it in about 30 to 60 seconds and proposes categories, prices, sizes, spice levels, and add-ons. Nothing is saved until the owner checks the list, edits names/prices, switches off items, and taps Import. Products already on the menu are skipped. For a PDF menu, screenshot each page.
- Categories: menu sections shown on the tablet and digital menu. Click a category (or Edit) to rename it or change its sort order; "Delete category" works only when it has no products.
- Promotions (owner/manager), button "New promo": discounts in percent (with an optional maximum) or rupiah, for the whole order, chosen categories, or chosen products, with an optional minimum spend, days of the week, and hours (happy hour; windows can pass midnight). Choose where it works: cashier tablet and/or digital menu. One promo per order; the biggest discount wins on the digital menu automatically; on the tablet the cashier taps "Add discount" and picks a promo. A manual discount (percent or rupiah) on the tablet needs a reason, and a cashier needs a manager's or owner's approval PIN. Tax is calculated after the discount. Switch a promo off any time; deleting it keeps past orders' discounts. Coupons: fill in "Coupon code" (e.g. HEMAT20) and the promo only applies when the code is typed: customers type it at digital menu checkout ("Have a coupon?"), and the cashier types it in the tablet's Discount dialog. Optional "Maximum uses" (total orders) and "Valid from/until" dates. The promo card shows how many times it was used and has "Code" and "Link" copy buttons; the link (menu address + ?coupon=CODE) opens the digital menu with the coupon ready, which is ideal for Instagram/TikTok/WhatsApp posts. If an automatic promo gives a bigger discount, that one wins.
- Tables & QR (button "Add tables"): tables grouped by area (Indoor, Outdoor, Rooftop, or any name). Add one table or many at once (code prefix, first number, how many, seats). Each table has its own QR code that opens the digital menu with the table filled in; "Print QR" prints an A4 sheet per area. Table numbers must be unique across areas because the tablet and orders identify tables by number. This list is the only source: the digital menu and the tablet accept only table numbers listed here (a customer typing a number that isn't here is told to check the number on the table). Click a table to edit its code, name, seats, or area, or "Delete table" (its printed QR stops working; switch it off instead to pause it). "Edit area" next to an area name renames the area (using another area's name merges them) or deletes the area with all its tables.
- Outlet settings: profile (names, tagline, phone, address, logo printed on receipts, banner for the digital menu), opening hours (the digital menu only takes orders during them), tax and order types (owner only), digital menu address and payment methods: Pay at cashier, QRIS (tap Upload image and pick the store's QRIS: the file from the bank or payment app, a screenshot, or a straight photo of the sticker; it is saved as soon as it is read and shows the merchant name, and iPhone HEIC photos need a screenshot or JPG instead; each digital menu order gets the exact amount plus a unique code of Rp 1 to 299, and the cashier tablet prints it with the exact amount, see below), Midtrans (needs a merchant key set by 1garis) — owner only. Tablet sync times.
- Your data (Outlet settings, owner only): "Download all data" gives one .zip file with everything in this outlet (settings, menu with options and photo links, tables, team list, promos, orders with items and payments, shifts and cash movements, expenses, audit log, problem reports). Passwords, PINs and tablet keys are never in it. Sync the tablet first so its latest sales are included. "Import data" moves such a file into this outlet, for example when changing to a new Mangalli app: it only works while the outlet has no menu and no orders, the file must have no open shift (close shifts and sync, then download again), and order history is matched to this outlet's team by email (ask 1garis Studio to add the team first, otherwise their history shows without a name). Branch outlets can't import. Totals and reports come out the same as before.
- Tablets (Outlet settings): every connected cashier tablet with its app version, last sync and "Up to date" or "Update available"; "APK" downloads the latest app for setting up a new tablet.
- What's new: after Mangalli is updated, a card at the bottom left lists the changes once per browser; "Got it" closes it. The dashboard is always the newest version, nothing to install.
- Team (owner): "Add cashier" adds a cashier yourself: name, email and a tablet password; they sign in on the cashier tablet (first time with internet, then offline too) and never get the dashboard. Owners, managers and viewers who need the dashboard are added by 1garis Studio. Edit existing operational roles, tablet passwords and approval PINs here; deactivate to sign someone out everywhere. "Branch access" at the bottom of a member's form lets them open other branches of the same brand with the same role (only branches where you are owner are listed), including signing in on those branches' tablets; their row then says "also N other branch". Members from another branch show "from <branch name>"; their name, password, PIN and role are managed at their own branch, and "Remove access" takes this branch away from them. Owners and managers also get a 6-digit "Approval PIN" (separate from the password, so a leaked password can't approve anything); each PIN must be different. The Approval PIN column shows Set / Not set. After setting a PIN, tap Sync now on the tablet.
- Branches (sidebar; owners, or anyone with access to more than one branch): one brand can run several outlets. The branch name at the top of the sidebar switches between branches you have access to; every page (orders, reports, expenses, tables, team, settings, Ask Eline) then shows only that branch. The Branches page compares branches side by side (sales, paid orders, average order, profit) for Today, 7 days, 30 days or This month, with "Open" to switch. "Add branch" (owner): name, address, phone; the new branch copies the outlet profile, opening hours, tax and order types and the whole menu, starts with Pay at cashier only, and has its own outlet code for connecting a tablet, its own tables and QR codes, digital menu, shifts and stock. Each branch is its own Mangalli subscription; 1garis Studio adds it to the next invoice.
- Branch menu: the menu belongs to the main branch. Add or change products, photos, categories and options at the main branch and every branch updates right away. At a branch, the product form only sets that branch's price ("Price here"; the hint shows the main branch price, enter it again to follow the main price), status (Available, Sold out, Hidden) and stock; Categories are read only and Add product / Import with Eline are hidden. A product removed at the main branch is hidden at the branches; past orders keep it.
- Audit log (owner): tabs All, Money, Menu, Team & settings, plus search; 25 per page. Money, access, and menu changes with who did it and who approved it: voids, refunds, manual discounts, price changes, deleted categories/options, promo changes, tax and payment settings, team changes, shifts.
- Support: report a problem (payment, printer, sync, menu, something broke). Crashes on the tablet, data that couldn't sync, dashboard errors, and failed online-payment notices appear here automatically. Owners and managers mark reports resolved.

ROLES
- Owner: everything, including team, tax, payment settings, and the audit log.
- Manager: menu, promotions, tables, reports, shifts, outlet profile, opening hours; approves voids, refunds, manual discounts, and carrying open bills to the next shift on the tablet by typing their 6-digit approval PIN.
- Cashier (staff): sells on the tablet, sees Orders and Kitchen; voids, refunds, manual discounts, and carrying open bills need a manager's or owner's approval PIN (5 wrong PINs pause approvals for a minute).
- Viewer: Overview only.

CASHIER TABLET (Android app)
- Install the APK, then "Connect this tablet" with the outlet code plus an owner or manager email and password (needs internet the first time). The menu, tables, tax, and promos download for offline use. Keep the tablet's date and time automatic; a banner warns when the clock is wrong.
- App updates: the tablet checks for a new version when it opens and after each sync. A banner says "Mangalli x.y.z is ready"; "What's new" shows the changes with "Update now" or "Later" (Settings > Outlet & device also has "Check for updates" / "Update to x.y.z"). The first time, Android asks to allow Mangalli to install updates (turn on "Allow from this source", go back, tap Try again); then Android asks to tap Install. Orders, shifts, cashiers and settings stay on the tablet. When 1garis Studio marks an update as required (important fixes), the tablet shows it without "Later" until it is installed. Tablets with an app from before 0.8.0 need the new app installed once by hand (sync and close the shift first, uninstall the old app, install the new one, sign in again); after that, updates come by themselves.
- QRIS with the amount (needs the store QRIS uploaded in Outlet settings, then a tablet sync): in Charge or Receive payment choose QRIS; the tablet shows the QR code with the amount right away, and the customer scans it from the screen with any bank or e-wallet app (the amount fills in by itself). "Enlarge" shows it big to turn the tablet towards the customer; "Print" prints the same QR on a slip like a card machine. Printed bills (Save bill > print) also carry the QR for their total. Mangalli doesn't get a payment notice from QRIS, so confirm after the customer shows the success screen or the money appears in your QRIS app. If the printer can't print QR codes, show the store QRIS stand instead.
- Cashiers sign in once online (lock icon > Use another account); afterwards they can sign in offline.
- Shift: count the starting cash and open the shift before taking payments. Money taken from the drawer for expenses (e.g. gallon water, ice, gas) is recorded with "Cash in/out" on the Shift screen: amount + reason; a cashier's cash out needs a manager's approval PIN; cash in (e.g. extra small change) needs no PIN. Expected cash = starting cash + cash sales + cash in - cash out, so the drawer still balances; keep the receipt in the drawer. Each cash in/out syncs to the dashboard (Shifts and Audit log > Money) and prints on the shift report. At the end, count the drawer and close; a cash difference needs a note, and a cashier closing with cash short needs a manager's PIN. Open bills can move to the next shift (cashier needs approval). The shift report shows who opened and who closed the shift. Money counts in the shift that received it.
- Menu screen: search, category chips, and label chips "Best sellers" (star) and "Favourites" (thumbs up) that show only products with that label; the labels come from the dashboard product form (Highlights) and show as a star/thumbs-up icon on the product photo. Tap products (options open a sheet), Takeaway or Dine in with a table, customer name. "Save bill" keeps an open bill and sends new items to the kitchen printer; "Charge" takes payment by Cash (quick amounts, change shown), QRIS, Card, Transfer, or Other. After payment, "New order" returns to the Menu screen. Lowering an item already saved on a bill opens Void (reason + approval for cashiers).
- Orders screen: awaiting payment (digital menu), preparing, ready. Accept, mark ready, complete, receive payment, print receipt (reprints say COPY), or cancel. Cancelling a paid order records a refund and needs approval for cashiers.
- History: last 7 days of sales and shifts; reprint receipts and shift reports.
- Order sound on the tablet: while online it checks for digital menu orders every 15 seconds and plays the same chime (plus a message) when a new one arrives or one is paid online or at the dashboard cashier. Settings > Tablet mode > "Order sound" On/Off; switching it on plays a sample. It uses the tablet's notification volume.
- Settings: outlet and device, sync status and "Sync now", Tablet mode ("Keep screen on", on by default; "Lock to Mangalli" pins the app so Home, recent apps, and notifications are blocked; Android asks to confirm with "Got it"; "Unlock" needs a manager PIN when a cashier is signed in; unlock before pairing a printer or updating the app), Bluetooth printers (pair in Android Bluetooth first, then Choose receipt and kitchen printers, 58 mm), cashiers on this tablet, and "Report a problem".
- The tablet works without internet and syncs at the scheduled times, on demand, and at every shift close.

DIGITAL MENU
- A mobile website on the brand's own domain (e.g. menu.brand.web.id), set up by 1garis as part of the website service. Customers choose Dine in (table from the QR) or Takeaway, add items with options, and pay by the methods the owner enabled. Orders wait as "Awaiting payment" for 30 minutes and only reach the kitchen once paid; unpaid ones cancel themselves. Live promos show on the menu and apply automatically.

ASK ELINE (this assistant)
- Owners and managers: Eline reads the outlet's own data (sales and profit for any period with a comparison, orders, products, stock, shifts, expenses, promotions; the owner also the audit log) and can make Excel (.xlsx) or PDF files: a full sales report (profit & loss, sales by day, products), profit & loss, sales by day, products, orders, expenses, shifts, or stock. Files are built straight from the data, so the numbers match Reports; the download button appears in the chat and the file stays available for 7 days. Cashiers: orders, products and stock only. Viewers: how-to questions only.
- Eline can't change anything (menu, prices, orders, settings).

HELP
- For anything the dashboard can't do, or bugs, use Support > Report a problem; 1garis follows up.
`;
